### ISSUE TITLE
Upgrade to JHipster 7

### ISSUE THREAD

**Issue by JasonTypesCodes** [jhipster/generator-jhipster-micronaut#250] opened 2021-05-10 14:51 UTC
See: #233 

@atomfrede do you have a good feel for everything that is required for this move?

**Comment by atomfrede** [comment] 2021-05-10 14:55
Not yet. Would try to generate an application with jhipster 7 and see what's working and what's not.

**Comment by mraible** [comment] 2021-08-04 19:23
Added bug bounty to increase motivation. 😉

**Comment by kevintanhongann** [comment] 2022-08-09 04:30
I assume the issue is done and merged?

**Comment by mraible** [comment] 2022-08-09 04:43
Yes.

@mshima Please collect your bounty so we can close this issue.

**Comment by mshima** [comment] 2022-08-09 21:00
Bounty claimed https://opencollective.com/generator-jhipster/expenses/89839.

**Comment by mshima** [comment] 2022-08-09 21:03
I don't have permission to close the issue.

**Closed** 2022-08-09 21:04 UTC
Labels: $$ bug-bounty $$, dependencies, $500, main:v7

**Comment by DanielFran** [comment] 2022-08-10 08:33
@mshima approved

**Comment by mshima** [comment] 2022-08-10 09:37
@DanielFran thanks
